const EVENTS = {
  PLAYER_TAP: 'PLAYER_TAP',
  DAMAGE_CALCULATED: 'DAMAGE_CALCULATED',
  ENEMY_DEAD: 'ENEMY_DEAD',
  BOSS_DEAD: 'BOSS_DEAD',
  ITEM_DROP: 'ITEM_DROP',
  UPGRADE_APPLIED: 'UPGRADE_APPLIED',
  PRESTIGE_TRIGGERED: 'PRESTIGE_TRIGGERED',
  STATE_SYNC: 'STATE_SYNC',
  REWARD_GRANTED: 'REWARD_GRANTED'
};

module.exports = { EVENTS };
